### ISSUE TITLE
Google Sign in returns error

### ISSUE THREAD

**Issue by KalleHallden** [EXERLOG/exer_log#14]
When pressing the Google sign in button the app breaks.

This bug is fixed when signing in with Google works. Work on this in the [Login branch](https://github.com/KalleHallden/exer_log/tree/Login)

**Comment by Scount** [comment]
### Found Exception
When i am trying to login with google i get this exception:
`PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)`
 The code 10 is refered to a misconfiguration as described on the [official documentation](https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes).
### Firebase setup
I can only guess but maybe the sign-in configuration on firebase isn't finished. Did you set the SHA in firebase? Check `[this tutorial](https://youtu.be/1k-gITZA9CI?t=213)` for setting it up.

**Comment by KalleHallden** [comment]
Yeah I think that is the issue. I have set up SHA-1 key but it might be that I need to set up a production key or something

**Comment by Scount** [comment]
@KalleHallden I think i got the solution. I connected the app with my private Firebase and it worked like a charm.
I am using the [Firebase-CLI](https://firebase.google.com/docs/cli) for connecting the app with Firebase. But since the app is already connected, you should see something like that:
<img width="943" alt="firebase_google_sha" src="https://user-images.githubusercontent.com/13836859/184244019-f3f276a7-2e20-49cf-b7c6-3cd88d1f0f6e.png">
Now we need to set the SHA-1 and SHA-256 key. For getting them i found [this issue](https://stackoverflow.com/a/60804020) which worked for me. Since i am on a MacBook i used `./gradlew signingReport`.

After adding them simply use `flutter clean` and `flutter pub get`. After this login with google should work.

**Comment by KalleHallden** [comment]
@Scount awesome work man! Yeah I'll see if I can fix that in the coming days
