### ISSUE TITLE
Saved template removed when the original workout it was created from is deleted

### ISSUE THREAD

**Issue by ckelwin** [EXERLOG/exer_log#26]
Problem:
1. Create a new workout (A) and save it as a template (B).
2. The template is available to be used when starting a new exercise. [OK]
3. Delete workout (A).
4. Start a new workout. Notice that the template (B) is no longer available.

Suggestion:
The `template` should be separate from the original workout it was created from. The template should remain even when the workout is deleted.
Might also need a 'manage template' page to allow create/edit/delete of templates.

**Comment by KalleHallden** [comment]
Okay I see. Yeah that is a great idea to keep them separated. And to, like you said, also add a page for editing and creating templates. My end goal with templates has been to allow the user to setup full workout plans that could last anywhere from days to months to potentially years. Where the user can select how often to perform the workout, how the progression should occur (ie for every exercise the user should be able to set that reps should increase by 2 every two weeks and if the reps are more than some number, maybe 12 then it should increase the weight to a new reasonable weight where the user can do 2-3 reps. So that the progressive overload cycle can be somewhat automated). And further down the line this would provide the ability for users to share workout templates with each other.
